// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/orders/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/index.delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/index.patch').default>>>>
    }
    '/api/orders/:id/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/status.patch').default>>>>
    }
    '/api/orders/:trackingCode': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[trackingCode].get').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.post').default>>>>
    }
    '/api/statuses/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/statuses/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/statuses/[id].patch').default>>>>
    }
    '/api/statuses': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/statuses/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/statuses/index.post').default>>>>
    }
    '/_ws': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/_ws').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}