services:
  nuxt:
    image: node:lts-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development
    command: sh -c "npm install && npm run prisma && npm run dev"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: delivery
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
