// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/8/2026, 12:55:52 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/amiraghyan99/projects/demo-delivery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/plugins/**/*.{js,ts,mjs}","/home/amiraghyan99/projects/demo-delivery/composables/**/*.{js,ts,mjs}","/home/amiraghyan99/projects/demo-delivery/utils/**/*.{js,ts,mjs}","/home/amiraghyan99/projects/demo-delivery/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/amiraghyan99/projects/demo-delivery/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;